import type { ScopeBinding } from '../types'

export const TEXTMATE: ScopeBinding[] = [
  { scope: ['keyword', 'storage.type'], role: 'keyword' },
  { scope: ['storage.modifier', 'meta.directive', 'entity.other.attribute-name.directive'], role: 'keyword.modifier' },
  { scope: ['keyword.control.return', 'keyword.control.throw', 'keyword.control.trycatch', 'keyword.control.flow', 'storage.modifier.async', 'storage.type.function.async'], role: 'keyword.action' },
  { scope: ['variable.other.readwrite', 'variable.other.object', 'variable.other.constant'], role: 'variable' },
  { scope: ['variable.language', 'variable.parameter.function.language.special'], role: 'variable.builtin' },
  { scope: ['variable.parameter'], role: 'parameter.binding' },
  { scope: ['variable.other.property', 'support.variable.property', 'meta.object-literal.key', 'meta.property-name', 'entity.other.attribute-name'], role: 'property' },
  { scope: ['entity.name.namespace'], role: 'module' },
  { scope: ['entity.name.tag'], role: 'tag' },
  { scope: ['entity.name.type', 'entity.name.class', 'support.type', 'support.class'], role: 'type.reference' },
  { scope: ['meta.class entity.name.type', 'meta.interface entity.name.type', 'meta.type.declaration entity.name.type', 'entity.name.type.alias', 'entity.name.type.interface'], role: 'type.definition' },
  { scope: ['entity.name.function'], role: 'function.definition' },
  { scope: ['support.function', 'meta.function-call entity.name.function', 'meta.function-call.generic entity.name.function'], role: 'function.call' },
  { scope: ['support.function.builtin', 'entity.name.function.decorator'], role: 'function.definition' },
  { scope: ['constant.numeric'], role: 'number' },
  { scope: ['constant.language', 'entity.name.constant', 'support.class.component'], role: 'constant' },
  { scope: ['string', 'constant.character'], role: 'string' },
  { scope: ['constant.character.escape', 'string.regexp'], role: 'escape' },
  { scope: ['keyword.operator'], role: 'operator' },
  { scope: ['punctuation', 'meta.brace', 'delimiter'], role: 'punctuation' },
  { scope: ['comment'], role: 'comment' },
  { scope: ['markup.heading', 'markup.heading entity.name'], role: 'markup.heading' },
  { scope: ['markup.bold'], role: 'markup.strong' },
  { scope: ['markup.italic'], role: 'markup.italic' },
  { scope: ['markup.quote'], role: 'markup.quote' },
  { scope: ['markup.underline.link', 'string.other.link'], role: 'markup.link' },
  { scope: ['markup.raw'], role: 'markup.raw' },
]

// These are contributed by Python language providers, not by the theme itself.
export const LANGUAGE_SEMANTIC: Record<string, string> = {
  'magicFunction': 'function.call',
  'magicFunction.declaration': 'function.definition',
  'selfParameter': 'variable.builtin',
  'selfParameter.declaration': 'parameter.builtin',
  'clsParameter': 'variable.builtin',
  'clsParameter.declaration': 'parameter.builtin',
  'class.builtin': 'type.definition',
  'class.typeHint': 'type.reference',
  'class.decorator': 'attribute',
  'function.builtin': 'function.definition',
  'function.decorator': 'attribute',
  'property.decorator': 'variable',
}
