// @env node
import type { BuildMetadata } from './types'
import { Buffer } from 'node:buffer'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { spec, VARIANTS } from '../core/resolve'
import { pruneArtifacts } from './artifacts'
import { LIGHTWEIGHT_PORTS, lightweightArchivePath, lightweightPath } from './catalog'
import { COMPILER_VERSION, PACKAGE_VERSION, SOURCE_REF, VARIANT_LABELS } from './constants'
import { lightweightArtifacts } from './lightweight'
import { neovimData } from './neovim/emit'
import { INTEGRATIONS } from './neovim/integrations'
import { portReadme } from './readme'
import { lua } from './serialize'
import { compileTheme } from './styles'
import { vscodeTheme } from './vscode/emit'
import { zip } from './zip'

const root = fileURLToPath(new URL('../', import.meta.url))
const check = process.argv.includes('--check')
const outputFlag = process.argv.indexOf('--out')
const output = outputFlag < 0 ? join(root, 'dist/ports') : process.argv[outputFlag + 1]!
if (!output)
  throw new Error('--out needs a path')

function files(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? files(join(directory, entry.name)) : [join(directory, entry.name)]).sort()
}

function hash(content: string | Buffer): string {
  return createHash('sha256').update(content).digest('hex')
}

const inputs = [...files(join(root, 'ports')), join(root, 'shared/crc32.ts'), ...['color.ts', 'resolve.ts', 'spec.json', 'syntax.ts', 'types.ts'].map(path => join(root, 'core', path))].sort()
const digest = createHash('sha256')
for (const path of inputs) {
  digest.update(`${relative(root, path)}\0`)
  digest.update(readFileSync(path))
  digest.update('\0')
}
const metadata: BuildMetadata = {
  schemaVersion: 1,
  designVersion: spec.version,
  compilerVersion: COMPILER_VERSION,
  inputHash: digest.digest('hex'),
  sourceRepository: 'https://github.com/0froq/lig',
  sourceRef: SOURCE_REF,
  variants: VARIANTS,
  colorPolicy: 'srgb-constant-lh-chroma-reduce',
}
const themes = VARIANTS.map(compileTheme)
const artifacts: Record<string, string | Buffer> = {}
const json = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`

artifacts['neovim/lua/lig_preview/generated.lua'] = `-- Generated by LiG compiler. Do not edit.\nreturn ${lua(neovimData(themes, metadata))}\n`
for (const path of files(join(root, 'ports/neovim/runtime')))
  artifacts[`neovim/${relative(join(root, 'ports/neovim/runtime'), path)}`] = readFileSync(path, 'utf8')
artifacts['neovim/colors/lig-preview.lua'] = 'require("lig_preview").load()\n'
for (const theme of themes)
  artifacts[`neovim/colors/lig-preview-${theme.variant}.lua`] = `require("lig_preview").load({ style = ${lua(theme.variant)} })\n`
artifacts['neovim/lua/lualine/themes/lig-preview.lua'] = 'return require("lig_preview.statusline").lualine()\n'
artifacts['neovim/lua/lightline/colorscheme/lig_preview.lua'] = 'return require("lig_preview.statusline").lightline()\n'
artifacts['neovim/autoload/lightline/colorscheme/lig_preview.vim'] = 'let s:palette = v:lua.require("lightline.colorscheme.lig_preview")\nlet g:lightline#colorscheme#lig_preview#palette = lightline#colorscheme#fill(s:palette)\n'
for (const theme of themes) {
  artifacts[`neovim/lua/lualine/themes/lig-preview-${theme.variant}.lua`] = `return require("lig_preview.statusline").lualine(${lua(theme.variant)})\n`
  const suffix = theme.variant.replaceAll('-', '_')
  artifacts[`neovim/lua/lightline/colorscheme/lig_preview_${suffix}.lua`] = `return require("lig_preview.statusline").lightline(${lua(theme.variant)})\n`
  artifacts[`neovim/autoload/lightline/colorscheme/lig_preview_${suffix}.vim`] = `let s:palette = v:lua.require("lightline.colorscheme.lig_preview_${suffix}")\nlet g:lightline#colorscheme#lig_preview_${suffix}#palette = lightline#colorscheme#fill(s:palette)\n`
}
artifacts['neovim/LICENSE'] = readFileSync(join(root, 'ports/licenses/Apache-2.0.txt'), 'utf8')
artifacts['neovim/README.md'] = portReadme('neovim', metadata)

artifacts['vscode/package.json'] = json({
  name: 'theme-lig-preview',
  displayName: 'LiG Preview',
  publisher: 'froQ',
  version: PACKAGE_VERSION,
  description: 'Preview of the unified OKLCH LiG theme ports',
  license: 'MIT',
  engines: { vscode: '^1.107.0' },
  categories: ['Themes'],
  repository: { type: 'git', url: 'https://github.com/0froq/vscode-theme-LiG-preview' },
  contributes: { themes: themes.map(theme => ({ label: VARIANT_LABELS[theme.variant], uiTheme: theme.mode === 'dark' ? 'vs-dark' : 'vs', path: `./themes/lig-${theme.variant}.json` })) },
})
for (const theme of themes)
  artifacts[`vscode/themes/lig-${theme.variant}.json`] = json(vscodeTheme(theme, VARIANT_LABELS[theme.variant]))
artifacts['vscode/LICENSE.md'] = readFileSync(join(root, 'ports/licenses/MIT-vscode.txt'), 'utf8')
artifacts['vscode/README.md'] = portReadme('vscode', metadata)
artifacts['vscode/.vscodeignore'] = '.git/**\n.github/**\n'
for (const port of ['neovim', 'vscode']) {
  artifacts[`${port}/lig-build.json`] = json({
    ...metadata,
    port,
    packageVersion: PACKAGE_VERSION,
    files: Object.fromEntries(Object.entries(artifacts).filter(([path]) => path.startsWith(`${port}/`)).map(([path, content]) => [path.slice(port.length + 1), hash(content)])),
    coverage: port === 'neovim' ? { integrations: Object.fromEntries(Object.entries(INTEGRATIONS).map(([name, integration]) => [name, { plugin: integration.plugin, groupCount: Object.keys(integration.groups).length }])), statuslines: ['lualine', 'lightline'], runtime: 'native Lua', syntax: ['classic', 'Tree-sitter', 'LSP'] } : { syntax: ['TextMate', 'semantic tokens'], runtime: 'declarative JSON' },
  })
}
const lightweight: Record<string, string | Buffer> = lightweightArtifacts(themes)
for (const port of LIGHTWEIGHT_PORTS) {
  const entries = Object.fromEntries(VARIANTS.map((variant) => {
    const path = lightweightPath(port, variant)
    return [path, lightweight[path]!]
  }))
  lightweight[lightweightArchivePath(port)] = zip(entries)
}
lightweight['README.md'] = readFileSync(join(root, 'ports/lightweight/README.md'), 'utf8')
lightweight['manifest.json'] = json({
  ...metadata,
  sourceRef: 'codex/lig-core-tokens',
  port: 'lightweight',
  files: Object.fromEntries(Object.entries(lightweight).map(([path, content]) => [path, hash(content)])),
})
for (const [path, content] of Object.entries(lightweight))
  artifacts[`lightweight/${path}`] = content

artifacts['manifest.json'] = json({ ...metadata, files: Object.fromEntries(Object.entries(artifacts).map(([path, content]) => [path, hash(content)])) })
function writeArtifacts(directory: string, artifacts: Record<string, string | Buffer>): void {
  pruneArtifacts(directory, artifacts, check)
  for (const [path, content] of Object.entries(artifacts)) {
    const target = join(directory, path)
    if (check) {
      if (!existsSync(target) || !readFileSync(target).equals(typeof content === 'string' ? Buffer.from(content) : content))
        throw new Error(`Artifact differs: ${target}`)
    }
    else {
      mkdirSync(dirname(target), { recursive: true })
      writeFileSync(target, content)
    }
  }
}
writeArtifacts(output, artifacts)
// Custom --out builds remain isolated; the standard build also serves identical bytes.
if (outputFlag < 0)
  writeArtifacts(join(root, 'public/ports'), lightweight)
process.stdout.write(`${check ? 'Checked' : 'Generated'} ${Object.keys(artifacts).length} artifacts; input ${metadata.inputHash}\n`)
