// Shared semantic-token intent; adapters translate native selector vocabulary.
export const SEMANTIC_TYPES: Record<string, string> = {
  namespace: 'module',
  class: 'type.reference',
  enum: 'constant',
  interface: 'type.reference',
  struct: 'type.reference',
  typeParameter: 'type.reference',
  type: 'type.reference',
  parameter: 'variable',
  variable: 'variable',
  property: 'property',
  enumMember: 'constant',
  decorator: 'attribute',
  event: 'function.call',
  function: 'function.call',
  method: 'function.call',
  macro: 'function.definition',
  label: 'constant',
  comment: 'comment',
  string: 'string',
  keyword: 'keyword',
  number: 'number',
  regexp: 'escape',
  operator: 'operator',
  boolean: 'constant',
}

/** Semantic declarations override the role, while modifiers preserve its color. */
export const DECLARATIONS: Record<string, string> = {
  namespace: 'module.definition',
  class: 'type.definition',
  enum: 'type.definition',
  interface: 'type.definition',
  struct: 'type.definition',
  typeParameter: 'type.definition',
  type: 'type.definition',
  parameter: 'parameter.binding',
  property: 'parameter.binding',
  enumMember: 'constant.builtin',
  event: 'function.definition',
  function: 'function.definition',
  method: 'function.definition',
}
