import type { ThemeIR } from '../types'
import { contrast } from '../../core/color'
import { requireToken } from '../styles'

export const ANSI_NAMES = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white'] as const
export const heading = (theme: ThemeIR, prefix = '#'): string => `${prefix} Generated by LiG. Variant: ${theme.variant}. Edit core/spec.json, not this file.\n`
export const color = requireToken

export function onColor(theme: ThemeIR, background: string): string {
  return ['text.strong', 'text.inverse'].map(token => color(theme, token)).sort((a, b) => contrast(b, background) - contrast(a, background))[0]!
}

export function rgb(hex: string): string {
  return [1, 3, 5].map(offset => Number.parseInt(hex.slice(offset, offset + 2), 16)).join(' ')
}
