import type { HighlightBinding } from '../types'
import { SYNTAX_CAPTURES } from '../../core/syntax'
import { STYLES } from '../styles'

export const BASE: Record<string, HighlightBinding> = {
  Normal: { fg: 'text.primary', bg: 'surface.canvas' },
  NormalNC: { fg: 'text.primary', bg: 'surface.canvas' },
  NormalFloat: { fg: 'text.primary', bg: 'surface.floating' },
  FloatBorder: { fg: 'border.default', bg: 'surface.floating' },
  FloatTitle: { fg: 'text.strong', bg: 'surface.floating', bold: true },
  WinSeparator: { fg: 'border.divider' },
  SignColumn: { bg: 'surface.canvas' },
  EndOfBuffer: { fg: 'surface.canvas' },
  ColorColumn: { bg: 'surface.raised' },
  CursorLine: { bg: 'surface.raised' },
  CursorColumn: { bg: 'surface.raised' },
  Cursor: { reverse: true },
  TermCursor: { reverse: true },
  LineNr: { fg: 'text.subtle' },
  LineNrAbove: { link: 'LineNr' },
  LineNrBelow: { link: 'LineNr' },
  CursorLineNr: { fg: 'text.strong', bold: true },
  CursorLineSign: { link: 'CursorLineNr' },
  CursorLineFold: { link: 'CursorLineNr' },
  Visual: { bg: 'surface.selection' },
  VisualNOS: { link: 'Visual' },
  Search: { bg: 'surface.search.other' },
  CurSearch: { bg: 'surface.search.match', fg: 'text.strong' },
  IncSearch: { link: 'CurSearch' },
  Substitute: { bg: 'surface.substitute', fg: 'text.inverse' },
  MatchParen: { fg: 'text.strong', bold: true, underline: true },
  Pmenu: { fg: 'text.primary', bg: 'surface.floating' },
  PmenuSel: { fg: 'text.strong', bg: 'surface.selection' },
  PmenuSbar: { bg: 'surface.raised' },
  PmenuThumb: { bg: 'text.subtle' },
  PmenuMatch: { fg: 'text.strong', bold: true },
  PmenuMatchSel: { link: 'PmenuMatch' },
  StatusLine: { fg: 'text.primary', bg: 'surface.status' },
  StatusLineNC: { fg: 'text.subtle', bg: 'surface.status' },
  WinBar: { link: 'StatusLine' },
  WinBarNC: { link: 'StatusLineNC' },
  TabLine: { link: 'StatusLineNC' },
  TabLineFill: { bg: 'surface.canvas' },
  TabLineSel: { fg: 'text.strong', bg: 'surface.raised', bold: true },
  Folded: { fg: 'text.subtle', bg: 'surface.folded' },
  FoldColumn: { fg: 'text.subtle', bg: 'surface.canvas' },
  NonText: { fg: 'text.dim' },
  Whitespace: { fg: 'text.dim' },
  SpecialKey: { fg: 'text.subtle' },
  Conceal: { fg: 'text.subtle' },
  Directory: { fg: 'accent.primary' },
  Title: { fg: 'text.strong', bold: true },
  ErrorMsg: { fg: 'diagnostic.error' },
  WarningMsg: { fg: 'diagnostic.warning' },
  MoreMsg: { fg: 'diagnostic.info' },
  Question: { fg: 'diagnostic.info' },
  Identifier: { role: 'variable' },
  Variable: { role: 'variable' },
  Property: { role: 'property' },
  Keyword: { role: 'keyword' },
  Statement: { role: 'keyword' },
  Conditional: { role: 'keyword' },
  Repeat: { role: 'keyword' },
  Include: { role: 'keyword' },
  PreProc: { role: 'keyword.directive' },
  Define: { role: 'keyword.directive' },
  StorageClass: { role: 'keyword.modifier' },
  Type: { role: 'type.reference' },
  Typedef: { role: 'type.definition' },
  Structure: { role: 'type.reference' },
  Function: { role: 'function.call' },
  Exception: { role: 'keyword.action' },
  Constant: { role: 'constant' },
  Number: { role: 'number' },
  Float: { role: 'number' },
  Boolean: { role: 'constant' },
  String: { role: 'string' },
  Character: { role: 'string' },
  Operator: { role: 'operator' },
  Delimiter: { role: 'punctuation' },
  Comment: { role: 'comment' },
  SpecialComment: { role: 'comment', italic: true },
  Special: { role: 'escape' },
  SpecialChar: { role: 'escape' },
  Todo: { role: 'comment.todo', bold: true },
  Underlined: { underline: true },
  Bold: { bold: true },
  Italic: { italic: true },
}

const roleByToken = Object.fromEntries(Object.entries(STYLES)
  .filter(([, style]) => style.foreground)
  .map(([role, style]) => [style.foreground!, role]))

export const CAPTURES: Record<string, HighlightBinding> = Object.fromEntries(
  Object.entries(SYNTAX_CAPTURES).map(([capture, token]) => {
    const role = roleByToken[token]
    if (!role)
      throw new Error(`Capture has no shared style: ${capture} -> ${token}`)
    return [`@${capture}`, { role }]
  }),
)

Object.assign(CAPTURES, {
  '@function.builtin': { role: 'function.definition' },
  '@function.macro': { role: 'function.definition' },
  '@type.builtin': { role: 'type.reference' },
  '@comment.note': { role: 'comment.note' },
  '@markup': { role: 'text' },
  '@markup.heading': { role: 'markup.heading' },
  '@markup.strong': { role: 'markup.strong' },
  '@markup.italic': { role: 'markup.italic' },
  '@markup.quote': { role: 'markup.quote' },
  '@markup.link': { role: 'markup.link' },
  '@markup.link.url': { role: 'markup.link' },
  '@markup.link.label': { role: 'text' },
  '@markup.raw': { role: 'markup.raw' },
  '@markup.strikethrough': { strikethrough: true },
  '@markup.underline': { underline: true },
})
