/** Legacy website names map to core roles, never to separately authored colors. */
export const ROLE_ALIASES = {
  bg: 'surface.canvas',
  bg_alt: 'surface.raised',
  bg_float: 'surface.floating',
  bg_reversed: 'surface.inverse',
  bg_highlight: 'surface.highlight',
  bg_selection: 'surface.selection',
  bg_folded: 'surface.folded',
  bg_search: 'surface.search',
  bg_substitute: 'surface.substitute',
  bg_statusline: 'surface.status',
  fg: 'text.primary',
  fg_secondary: 'text.secondary',
  fg_muted: 'text.subtle',
  fg_dim: 'text.dim',
  fg_reversed: 'text.inverse',
  fg_strong: 'text.strong',
  fg_sidebar: 'text.subtle',
  border: 'border.default',
  divider: 'border.divider',
  shadow: 'shadow.default',
  accent1: 'accent.primary',
  accent2: 'accent.secondary',
  keyword: 'syntax.keyword',
  string: 'syntax.string',
  comment: 'syntax.comment',
  type: 'syntax.type',
  constant: 'syntax.constant',
  number: 'syntax.number',
  func: 'syntax.function',
  method: 'syntax.method',
  operator: 'syntax.operator',
  special: 'syntax.special',
  variable: 'syntax.variable',
  property: 'syntax.property',
  tag: 'syntax.tag',
} as const

export const GROUP_ALIASES = {
  git: { add: 'git.add', delete: 'git.delete', change: 'git.change', ignore: 'git.ignore' },
  diag: { error: 'diagnostic.error', warn: 'diagnostic.warning', info: 'diagnostic.info', hint: 'diagnostic.hint', ok: 'diagnostic.ok' },
  msg: { success: 'message.success', failure: 'message.failure', warning: 'message.warning', info: 'message.info' },
  mode: { normal: 'mode.normal', insert: 'mode.insert', visual: 'mode.visual', replace: 'mode.replace', command: 'mode.command', other: 'mode.other' },
} as const

export const SEMANTIC_KEYS = [
  'bg',
  'bg_alt',
  'bg_float',
  'fg',
  'fg_secondary',
  'fg_muted',
  'fg_dim',
  'fg_strong',
  'border',
  'accent1',
  'accent2',
  'diag.error',
  'diag.warn',
  'diag.info',
  'diag.hint',
  'git.add',
  'git.delete',
  'git.change',
] as const
